"""add job collection table and relationships

Revision ID: 15978facfda5
Revises: 5ceee9c9743c
Create Date: 2025-10-25 22:28:41.311177

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "15978facfda5"
down_revision = "5ceee9c9743c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_collections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("job_listing_id", sa.Integer(), nullable=False),
        sa.Column("added_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_listing_id"],
            ["job_listings.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "job_listing_id", name="uix_user_job_listing"),
    )
    # Drop foreign key constraint BEFORE altering column type
    op.drop_constraint("resumes_user_id_fkey", "resumes", type_="foreignkey")
    # Now alter the column type with explicit conversion
    op.alter_column(
        "resumes",
        "user_id",
        existing_type=sa.INTEGER(),
        type_=sa.String(),
        existing_nullable=False,
        postgresql_using="user_id::varchar",
    )
    # Create new foreign key constraint with correct type
    op.create_foreign_key(None, "resumes", "user_profiles", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("job_collections")
    # Drop foreign key constraint BEFORE altering column type
    op.drop_constraint(None, "resumes", type_="foreignkey")
    # Now alter the column type back to INTEGER with explicit conversion
    op.alter_column(
        "resumes",
        "user_id",
        existing_type=sa.String(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        postgresql_using="user_id::integer",
    )
    # Create old foreign key constraint
    op.create_foreign_key(
        "resumes_user_id_fkey", "resumes", "users", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###
