"""add processRun and Resume table

Revision ID: a9eaf147fe1c
Revises: 07f67e8408b6
Create Date: 2025-10-20 23:58:03.135122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9eaf147fe1c'
down_revision = '07f67e8408b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processing_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('llm_model', sa.String(), nullable=True),
    sa.Column('embed_model', sa.String(), nullable=True),
    sa.Column('code_version_hash', sa.String(), nullable=True),
    sa.Column('params_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=True),
    sa.Column('parsed_json', sa.JSON(), nullable=True),
    sa.Column('vector_doc_id', sa.String(), nullable=True),
    sa.Column('processing_run_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['processing_run_id'], ['processing_runs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resumes')
    op.drop_table('processing_runs')
    # ### end Alembic commands ###
