"""add is_default to resumes table

Revision ID: add_is_default_to_resumes
Revises: a9eaf147fe1c
Create Date: 2025-01-23 12:00:00.000000

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "add_is_default_to_resumes"
down_revision = "c2f8a3b9d4e1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "resumes", sa.Column("is_default", sa.Boolean(), nullable=False, default=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("resumes", "is_default")
    # ### end Alembic commands ###
