"""add contact fields to user profile

Revision ID: c2f8a3b9d4e1
Revises: 15978facfda5
Create Date: 2025-10-25 23:00:00.000000

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c2f8a3b9d4e1"
down_revision = "15978facfda5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_profiles", sa.Column("contact_name", sa.String(), nullable=True)
    )
    op.add_column(
        "user_profiles", sa.Column("contact_email", sa.String(), nullable=True)
    )
    op.add_column(
        "user_profiles", sa.Column("contact_phone_number", sa.String(), nullable=True)
    )
    op.add_column(
        "user_profiles", sa.Column("contact_location", sa.String(), nullable=True)
    )

    # Populate contact_name and contact_email for existing users
    op.execute(
        """
        UPDATE user_profiles 
        SET contact_name = name, 
            contact_email = email
        WHERE contact_name IS NULL
    """
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_profiles", "contact_location")
    op.drop_column("user_profiles", "contact_phone_number")
    op.drop_column("user_profiles", "contact_email")
    op.drop_column("user_profiles", "contact_name")
    # ### end Alembic commands ###
