"""add s3 fields to resumes table

Revision ID: add_s3_fields_to_resumes
Revises: add_is_default_to_resumes
Create Date: 2025-01-23 12:00:00.000000

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "add_s3_fields_to_resumes"
down_revision = "add_is_default_to_resumes"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("resumes", sa.Column("s3_bucket", sa.String(), nullable=True))
    op.add_column("resumes", sa.Column("s3_key", sa.String(), nullable=True))
    op.add_column("resumes", sa.Column("original_filename", sa.String(), nullable=True))
    op.add_column("resumes", sa.Column("file_size", sa.BigInteger(), nullable=True))
    op.add_column("resumes", sa.Column("content_type", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("resumes", "content_type")
    op.drop_column("resumes", "file_size")
    op.drop_column("resumes", "original_filename")
    op.drop_column("resumes", "s3_key")
    op.drop_column("resumes", "s3_bucket")
    # ### end Alembic commands ###
