"""create skill gap report status to track gen progress

Revision ID: bc577da832b5
Revises: cf902ce3e55c
Create Date: 2025-11-01 09:30:50.436238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc577da832b5'
down_revision = 'cf902ce3e55c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill_gap_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('job_listing_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_listing_id'], ['job_listings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'job_listing_id', name='uix_gap_status_user_job')
    )
    op.create_index(op.f('ix_skill_gap_statuses_job_listing_id'), 'skill_gap_statuses', ['job_listing_id'], unique=False)
    op.create_index(op.f('ix_skill_gap_statuses_status'), 'skill_gap_statuses', ['status'], unique=False)
    op.create_index(op.f('ix_skill_gap_statuses_user_id'), 'skill_gap_statuses', ['user_id'], unique=False)
    op.drop_index(op.f('idx_learning_items_skill_id'), table_name='learning_items')
    op.drop_index(op.f('idx_report_learning_items_learning_item_id'), table_name='report_learning_items')
    op.drop_index(op.f('idx_report_learning_items_report_id'), table_name='report_learning_items')
    op.drop_index(op.f('ix_resumes_status'), table_name='resumes')
    op.alter_column('skill_gap_reports', 'score',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.drop_index(op.f('idx_skill_gap_reports_job_listing_id'), table_name='skill_gap_reports')
    op.drop_index(op.f('idx_skill_gap_reports_resume_id'), table_name='skill_gap_reports')
    op.drop_index(op.f('idx_tasks_learning_item_id'), table_name='tasks')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_tasks_learning_item_id'), 'tasks', ['learning_item_id'], unique=False)
    op.create_index(op.f('idx_skill_gap_reports_resume_id'), 'skill_gap_reports', ['resume_id'], unique=False)
    op.create_index(op.f('idx_skill_gap_reports_job_listing_id'), 'skill_gap_reports', ['job_listing_id'], unique=False)
    op.alter_column('skill_gap_reports', 'score',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.create_index(op.f('ix_resumes_status'), 'resumes', ['status'], unique=False)
    op.create_index(op.f('idx_report_learning_items_report_id'), 'report_learning_items', ['report_id'], unique=False)
    op.create_index(op.f('idx_report_learning_items_learning_item_id'), 'report_learning_items', ['learning_item_id'], unique=False)
    op.create_index(op.f('idx_learning_items_skill_id'), 'learning_items', ['skill_id_fk'], unique=False)
    op.drop_index(op.f('ix_skill_gap_statuses_user_id'), table_name='skill_gap_statuses')
    op.drop_index(op.f('ix_skill_gap_statuses_status'), table_name='skill_gap_statuses')
    op.drop_index(op.f('ix_skill_gap_statuses_job_listing_id'), table_name='skill_gap_statuses')
    op.drop_table('skill_gap_statuses')
    # ### end Alembic commands ###
